# codemagic.yaml - Valid Android Build Configuration
workflows:
  android-build:
    name: ClashBerry Android
    environment:
      groups:
        - android_sdk_license
        #- keystore_credentials  # Uncomment for release signing
      vars:
        ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"

    # Corrected triggering syntax
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Setup Android SDK
        script: |
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        script: |
          cd ./ClashBerry
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - ./ClashBerry/app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - jktipra@gmail.com