# FINAL WORKING CONFIGURATION
workflows:
  android-build:
    name: Android Production Build
    environment:
      groups:
        - android_sdk_license
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
    scripts:
      - name: Prepare Environment
        script: |
          cd ./ClashBerry
          chmod +x gradlew
          ./gradlew --version

      - name: Build APK
        script: |
          cd ./ClashBerry
          ./gradlew assembleDebug

    artifacts:
      - ./ClashBerry/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - jktipra@gmail.com